### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by celil-kj** [rspeer/csc-pysparse#1]
Can this library be installed for python3?

**Comment by rspeer** [comment]
Nope, sorry.

I doubt that porting csc-pysparse to Python 3 would be worthwhile at this point, because it would only be usable by people who have managed to get NumPy to run on Python 3. Which I know is now possible, but it's not in an official release yet.

You may want to look at the progress of SciPy on Python 3 instead, and use SciPy's sparse matrix library.

**Comment by halflings** [comment]
Hi!

Since Python 3 is now democratized, and numpy/pandas/sklearn/more-or-less-anything runs on Python 3, would it be possible to port this to Python 3?

I want to use python-recsys but it depends on csc-pysparse.

**Comment by rspeer** [comment]
The landscape has definitely changed in 5 years. I use Python 3 almost exclusively now. However, along the same lines, I can't imagine why you'd want to use pysparse in 2015. SciPy is much better at sparse matrix computations now.

Keep in mind that I'm not an author of pysparse, I just packaged it so it could be installed using pip. I'd have no better plan than anyone else for porting pysparse to Python 3. It seems that it would be easier to port python-recsys to SciPy.
